### ISSUE TITLE
Which file contains QEBA attack algorithm?

### ISSUE THREAD

**Issue by machanic** [AI-secure/QEBA#1]
The foolbox folder has many files. Which file contains QEBA attack algorithm?

**Comment by HuichenLi** [comment]
Hi! The QEBA attack is implemented under the name "BAPP_custom" in the repo: [[link](https://github.com/AI-secure/QEBA/blob/master/foolbox-based/foolbox/attacks/bapp_custom.py)]

**Comment by machanic** [comment]
I notice that in https://github.com/AI-secure/QEBA/blob/master/foolbox-based/foolbox/attacks/bapp_custom.py#L40
It writes `Paper link: https://arxiv.org/abs/1904.02144`. However, this paper indicates the paper with title <HopSkipJumpAttack: A Query-Efficient Decision-Based Attack> ,rather than QEBA paper: QEBA:Query-Efficient Boundary-Based Blackbox Attack.

Are you sure BAPP_custom is QEBA algorithm?

**Comment by HuichenLi** [comment]
Of course. The paper link shown in the code is our baseline method HopSkipJumpAttack. Our code is modified based on their method so that's why we add their paper link there as an acknowledgement.
