### ISSUE TITLE
How to support targeted attack?

### ISSUE THREAD

**Issue by machanic** [AI-secure/QEBA#2]
I notice that `is_adversarial` method in `adversarial.py` only uses `original_label`.(located in https://github.com/AI-secure/QEBA/blob/master/foolbox-based/foolbox/adversarial.py#L57)
There is no place to put the target class label? **How to support targeted attack in QEBA** and collect query count and success rate and distortion?

**Comment by machanic** [comment]
Also, the code of `attack = foolbox.attacks.BAPP_custom(fmodel, criterion=TargetClass(src_label))` is bug?? It indicates the true label is used as the target class label??
It is located in https://github.com/AI-secure/QEBA/blob/master/foolbox-based/main_pytorch.py#L134

**Comment by HuichenLi** [comment]
Please check [attack_setting.py](https://github.com/AI-secure/QEBA/blob/master/foolbox-based/attack_setting.py) for how we generate the source image and target image pairs as well as the labels. The generated pairs are used in [main_pytorch_multi.py](https://github.com/AI-secure/QEBA/blob/master/foolbox-based/main_pytorch_multi.py).
To run the attack, run `python3 main_pytorch_multi.py --use_gpu`. You can modify [line 33 and 34](https://github.com/AI-secure/QEBA/blob/master/foolbox-based/main_pytorch_multi.py#L33) to perform attacks on a different dataset and on a different number of source-target pairs.

**Comment by machanic** [comment]
I thought QEBA uses the file `main_pytorch.py` , rather than `main_pytorch_multi.py`, which file is the main file of **QEBA**?
Also, main_pytorch_multi.py has a **bug** in line: https://github.com/AI-secure/QEBA/blob/master/foolbox-based/main_pytorch_multi.py#L121
It uses `criterion=TargetClass(src_label))` no matther in untargeted attack or targeted attack! It should change to `criterion=TargetClass(tgt_label))` in targeted attack, and keep `src_label` in untargeted attack
