### ISSUE TITLE
Where is pretrained model file with pgen_type == 'NNGen768' and 'NNGen50'?

### ISSUE THREAD

**Issue by machanic** [AI-secure/QEBA#3]
In attack_settings.py (https://github.com/AI-secure/QEBA/blob/master/foolbox-based/attack_setting.py#L270), These files are not uploaded in this repo, please update them, thank you！

`p_gen.load('pca_gen_1000_imagenet.npy')`
`p_gen.load('pca_gen_5000_imagenet.npy')`
`p_gen.load('pca_gen_5000_imagenet.npy')` 
`p_gen.load_state_dict(torch.load('nn_gen_50_cifar.model'))` (https://github.com/AI-secure/QEBA/blob/master/foolbox-based/attack_setting.py#L114)
`p_gen.load_state_dict(torch.load('nn_gen_768_cifar.model'))` (https://github.com/AI-secure/QEBA/blob/master/foolbox-based/attack_setting.py#L117)

**Comment by HuichenLi** [comment]
Hi, 
You can use the training code (e.g., [train_pca_generator.py](https://github.com/AI-secure/QEBA/blob/master/foolbox-based/train_pca_generator.py)) to train a model of your own.
